<a href="https://colab.research.google.com/github/VASAVI1231/NumPy-Matrix-Operations/blob/main/Numpy_matrix_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Task 14 - NumPy Matrix Operations
# AI & ML Internship - VEDA Technology
# Student: Peddada Vasavi

import numpy as np

# -------------------------------------------------
# 1. Create Two Matrices
# -------------------------------------------------

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("========== MATRIX A ==========")
print(A)

print("\n========== MATRIX B ==========")
print(B)


# -------------------------------------------------
# 2. Matrix Addition
# -------------------------------------------------

addition = A + B

print("\n========== MATRIX ADDITION ==========")
print("A + B =")
print(addition)


# -------------------------------------------------
# 3. Matrix Subtraction
# -------------------------------------------------

subtraction = A - B

print("\n========== MATRIX SUBTRACTION ==========")
print("A - B =")
print(subtraction)


# -------------------------------------------------
# 4. Matrix Multiplication
# -------------------------------------------------
# @ performs mathematical matrix multiplication

matrix_multiplication = A @ B

print("\n========== MATRIX MULTIPLICATION ==========")
print("A @ B =")
print(matrix_multiplication)


# -------------------------------------------------
# 5. Matrix Multiplication using np.dot()
# -------------------------------------------------

dot_multiplication = np.dot(A, B)

print("\n========== MATRIX MULTIPLICATION USING np.dot() ==========")
print("np.dot(A, B) =")
print(dot_multiplication)


# -------------------------------------------------
# 6. Transpose of Matrix A
# -------------------------------------------------

transpose_A = A.T

print("\n========== TRANSPOSE OF MATRIX A ==========")
print("A.T =")
print(transpose_A)


# -------------------------------------------------
# 7. Transpose of Matrix B
# -------------------------------------------------

transpose_B = B.T

print("\n========== TRANSPOSE OF MATRIX B ==========")
print("B.T =")
print(transpose_B)


# -------------------------------------------------
# 8. Final Explanation
# -------------------------------------------------

print("\n========== EXPLANATION ==========")

print("1. Matrix addition adds corresponding elements.")
print("2. Matrix subtraction subtracts corresponding elements.")
print("3. Matrix multiplication follows row-by-column multiplication.")
print("4. Transpose changes rows into columns and columns into rows.")

========== MATRIX A ==========
[[1 2 3]
 [4 5 6]
 [7 8 9]]

========== MATRIX B ==========
[[9 8 7]
 [6 5 4]
 [3 2 1]]

========== MATRIX ADDITION ==========
A + B =
[[10 10 10]
 [10 10 10]
 [10 10 10]]

========== MATRIX SUBTRACTION ==========
A - B =
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

========== MATRIX MULTIPLICATION ==========
A @ B =
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

========== MATRIX MULTIPLICATION USING np.dot() ==========
np.dot(A, B) =
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

========== TRANSPOSE OF MATRIX A ==========
A.T =
[[1 4 7]
 [2 5 8]
 [3 6 9]]

========== TRANSPOSE OF MATRIX B ==========
B.T =
[[9 6 3]
 [8 5 2]
 [7 4 1]]

========== EXPLANATION ==========
1. Matrix addition adds corresponding elements.
2. Matrix subtraction subtracts corresponding elements.
3. Matrix multiplication follows row-by-column multiplication.
4. Transpose changes rows into columns and columns into rows.
